name: 'IronSpec: Governance Guard'
description: 'The "Iron Dome" for AI-Native Dev Shops. Enforces Notion Specs via Linear & GitHub.'
author: 'IronSpec'
branding:
  icon: 'shield'
  color: 'blue'
inputs:
  gemini_api_key:
    description: 'API Key for the Reasoning Engine'
    required: false
  linear_api_key:
    description: 'API Key for Audit Logging'
    required: true
  notion_api_key:
    description: 'API Key for fetching Specs'
    required: true
  github_token:
    description: 'GITHUB_TOKEN to post comments'
    required: true
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Dependencies (Secure)
      shell: bash
      run: pip install -r ${{ github.action_path }}/requirements.txt

    - name: Run Governance Guard
      shell: bash
      env:
        # API Keys
        GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
        LINEAR_API_KEY: ${{ inputs.linear_api_key }}
        NOTION_TOKEN: ${{ inputs.notion_api_key }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        
        # 👇 The big fix: Pass Context data to Python
        GITHUB_EVENT_PATH: ${{ github.event_path }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
      
      run: python ${{ github.action_path }}/.github/scripts/action-guard.py
